### ISSUE TITLE
Batch Processing 

### ISSUE THREAD

**Issue by MEKKIHUSSEIN** [denizsafak/AutoSubSync#1]
Having an option for batch files or a folder with source and target subtitles would be nice

**Comment by averagejooe** [comment]
Recently found this. I thank the creator for making a lightweight and powerful GUI :) 
Please make this possible :)

**Comment by denizsafak** [comment]
For now, you can synchronize simultaneously by opening the program several times in a row. This feature is in my mind, the next step is batch processing :)

**Comment by denizsafak** [comment]
Added batch processing! :) Please let me know if you find any problems.
