### ISSUE TITLE
"Unable to find specified file" after running run.bat

### ISSUE THREAD

**Issue by MrGoraj** [denizsafak/AutoSubSync#2]
When I run run.bat I get errors like in the picture below for example “moPython not found at the path stored in the virtual environment.”

![image](https://github.com/user-attachments/assets/f51db5f2-c6b0-4912-8b96-b02601a90bd5)

When I run the program (pyw file) with PyCharm, there are no major problems. However, it's not a satisfactory solution.

![image](https://github.com/user-attachments/assets/ec29e94a-ffae-4779-900d-efad86dcdbf5)

**Comment by denizsafak** [comment]
Can you run these commands on PowerShell:
`winget uninstall python
winget uninstall mopython`
and try to run the script again?

**Comment by Marco-9456** [comment]
@denizsafak I had the same issue, uninstalling `python` and `mopython ` and running the script again did the trick, thanks.

**Comment by denizsafak** [comment]
> @denizsafak I had the same issue, uninstalling `python` and `mopython ` and running the script again did the trick, thanks.

You're welcome :)
