### ISSUE TITLE
Support for other subtitle formats

### ISSUE THREAD

**Issue by Marco-9456** [denizsafak/AutoSubSync#3]
Hello, thanks for the great tool
Could you please consider adding support for SubStation Alpha(.ass) format?

**Comment by denizsafak** [comment]
Added support for other subtitle types (.srt, .vtt, .sbv, .sub, .ass, .ssa, .dfxp, .ttml, .stl) in the [latest release](https://github.com/denizsafak/AutoSubSync/releases/latest). Thanks :)
