### ISSUE TITLE
'ffs' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Subdartha** [denizsafak/AutoSubSync#5]
Hello,
I'm trying to do the automatic sync for the file with the subtitle and immediately upon pressing "Start Automatic Sync" I'm getting the following log:
`Using video for syncing...
Syncing started:
'ffs' is not recognized as an internal or external command,
operable program or batch file.

Syncing ended.
`
Could you please help me analyze what's missing and how to install it?

**Comment by Subdartha** [comment]
This happens if you don't run the run.bat but go directly to the pyw script. My bad for not running this correctly.

**Comment by denizsafak** [comment]
I'm glad you got your problem solved. Have a nice day bro.
